//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verdure.McpPlatform.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verdure.McpPlatform.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate 的本地化字符串。
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Bindings 的本地化字符串。
        /// </summary>
        public static string ActiveBindings {
            get {
                return ResourceManager.GetString("ActiveBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Connection 的本地化字符串。
        /// </summary>
        public static string AddConnection {
            get {
                return ResourceManager.GetString("AddConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Service 的本地化字符串。
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Xiaozhi Connection 的本地化字符串。
        /// </summary>
        public static string AddXiaozhiMcpEndpoint {
            get {
                return ResourceManager.GetString("AddXiaozhiMcpEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verdure MCP Platform 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Args 的本地化字符串。
        /// </summary>
        public static string Args {
            get {
                return ResourceManager.GetString("Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} binding(s) 的本地化字符串。
        /// </summary>
        public static string BindingsCount {
            get {
                return ResourceManager.GetString("BindingsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure external MCP service bindings 的本地化字符串。
        /// </summary>
        public static string ConfigureExternalServices {
            get {
                return ResourceManager.GetString("ConfigureExternalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection 的本地化字符串。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection deleted successfully 的本地化字符串。
        /// </summary>
        public static string ConnectionDeleted {
            get {
                return ResourceManager.GetString("ConnectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Binding 的本地化字符串。
        /// </summary>
        public static string CreateBinding {
            get {
                return ResourceManager.GetString("CreateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created 的本地化字符串。
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview of your MCP platform statistics and recent activity 的本地化字符串。
        /// </summary>
        public static string DashboardOverview {
            get {
                return ResourceManager.GetString("DashboardOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deactivate 的本地化字符串。
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Connection 的本地化字符串。
        /// </summary>
        public static string DeleteConnection {
            get {
                return ResourceManager.GetString("DeleteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this connection? All associated service bindings will also be deleted. 的本地化字符串。
        /// </summary>
        public static string DeleteConnectionConfirm {
            get {
                return ResourceManager.GetString("DeleteConnectionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Service 的本地化字符串。
        /// </summary>
        public static string DeleteService {
            get {
                return ResourceManager.GetString("DeleteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this service binding? 的本地化字符串。
        /// </summary>
        public static string DeleteServiceConfirm {
            get {
                return ResourceManager.GetString("DeleteServiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred 的本地化字符串。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactive 的本地化字符串。
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactive Bindings 的本地化字符串。
        /// </summary>
        public static string InactiveBindings {
            get {
                return ResourceManager.GetString("InactiveBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid format 的本地化字符串。
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login to Get Started 的本地化字符串。
        /// </summary>
        public static string LoginToGetStarted {
            get {
                return ResourceManager.GetString("LoginToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage your Xiaozhi AI server connections 的本地化字符串。
        /// </summary>
        public static string ManageConnections {
            get {
                return ResourceManager.GetString("ManageConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage MCP services for this connection 的本地化字符串。
        /// </summary>
        public static string ManageServicesForConnection {
            get {
                return ResourceManager.GetString("ManageServicesForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCP Bindings 的本地化字符串。
        /// </summary>
        public static string McpBindings {
            get {
                return ResourceManager.GetString("McpBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCP Management 的本地化字符串。
        /// </summary>
        public static string McpManagement {
            get {
                return ResourceManager.GetString("McpManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCP Service Bindings 的本地化字符串。
        /// </summary>
        public static string McpServiceBindings {
            get {
                return ResourceManager.GetString("McpServiceBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MCP Services 的本地化字符串。
        /// </summary>
        public static string McpServices {
            get {
                return ResourceManager.GetString("McpServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No connections yet. Create your first Xiaozhi connection to get started! 的本地化字符串。
        /// </summary>
        public static string NoConnectionsYet {
            get {
                return ResourceManager.GetString("NoConnectionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data available 的本地化字符串。
        /// </summary>
        public static string NoDataMessage {
            get {
                return ResourceManager.GetString("NoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No servers yet. Create Xiaozhi Connection to get started! 的本地化字符串。
        /// </summary>
        public static string NoServersYet {
            get {
                return ResourceManager.GetString("NoServersYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No services yet. Create your first MCP service binding! 的本地化字符串。
        /// </summary>
        public static string NoServicesYet {
            get {
                return ResourceManager.GetString("NoServicesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Started 的本地化字符串。
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A powerful platform for managing MCP (Model Context Protocol) services with Xiaozhi AI integration. 的本地化字符串。
        /// </summary>
        public static string PlatformDescription {
            get {
                return ResourceManager.GetString("PlatformDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Actions 的本地化字符串。
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Servers 的本地化字符串。
        /// </summary>
        public static string RecentServers {
            get {
                return ResourceManager.GetString("RecentServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field is required 的本地化字符串。
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service activated successfully 的本地化字符串。
        /// </summary>
        public static string ServiceActivated {
            get {
                return ResourceManager.GetString("ServiceActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service deactivated successfully 的本地化字符串。
        /// </summary>
        public static string ServiceDeactivated {
            get {
                return ResourceManager.GetString("ServiceDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service deleted successfully 的本地化字符串。
        /// </summary>
        public static string ServiceDeleted {
            get {
                return ResourceManager.GetString("ServiceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Name 的本地化字符串。
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Services for {0} 的本地化字符串。
        /// </summary>
        public static string ServicesFor {
            get {
                return ResourceManager.GetString("ServicesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation completed successfully 的本地化字符串。
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Bindings 的本地化字符串。
        /// </summary>
        public static string TotalBindings {
            get {
                return ResourceManager.GetString("TotalBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport 的本地化字符串。
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated 的本地化字符串。
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View All Connections 的本地化字符串。
        /// </summary>
        public static string ViewAllConnections {
            get {
                return ResourceManager.GetString("ViewAllConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Details 的本地化字符串。
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Services 的本地化字符串。
        /// </summary>
        public static string ViewServices {
            get {
                return ResourceManager.GetString("ViewServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Verdure MCP Platform 的本地化字符串。
        /// </summary>
        public static string WelcomeToPlatform {
            get {
                return ResourceManager.GetString("WelcomeToPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xiaozhi Connections 的本地化字符串。
        /// </summary>
        public static string XiaozhiMcpEndpoints {
            get {
                return ResourceManager.GetString("XiaozhiMcpEndpoints", resourceCulture);
            }
        }
    }
}
